// This file is automatically generated. Do not modify it manually.
import {FirebaseOptions} from 'firebase/app';

// Your web app's Firebase configuration
export const firebaseConfig: FirebaseOptions = {
  apiKey: 'AIzaSyA9TfjrCVnHnzCBNtCG7pUr6teCh94pLV4',
  appId: '1:241153045916:web:b2be25755ef0c2c9a58459',
  authDomain: 'studio-6340960820-47a50.firebaseapp.com',
  measurementId: 'G-LE5XQ1ZGH1',
  messagingSenderId: '241153045916',
  projectId: 'studio-6340960820-47a50',
};
